"""first revision

Revision ID: 653077837b71
Revises: 
Create Date: 2023-01-03 16:59:59.374406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653077837b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('idPost', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idPost')
    )
    op.create_table('votes',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idPost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPost'], ['posts.idPost'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idUser', 'idPost')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
